### ISSUE TITLE
incorporate total or daily patient counts into normalized change plots

### ISSUE THREAD

**Issue by ngehlenborg** [covidclinical/visualization-notebooks#4]
We should provide information about patient counts into these plots (either reporting a total n per country or showing the patient counts in addition to the site counts) to make it clear why some countries have curves that are different from the JHU data.

**Comment by keller-mark** [comment]
Fixed in https://github.com/covidclinical/visualization-notebooks/commit/224e642bd2ac86f80ef041881422342ad3644116 by showing the `new positive cases` counts above the number of site plot for each country.
